### ISSUE TITLE
.ino does not compile: draw.h missing.

### ISSUE THREAD

**Issue by olikraus** [embeddedadventures/EPD-200200B#1]
fatal error: draw.h: No such file or directory
 #include <draw.h>
                  ^
compilation terminated.

Please provide the missing file.h.
Or is there any other library or example code for 200x200 ePaper from embedded adventures?

**Comment by dr4nc3s** [comment]
Here's the link to the draw library. https://github.com/embeddedadventures/draw

I also made the edit to the description to include a link to the draw library. Thanks for pointing it out!

**Comment by olikraus** [comment]
Thanks
