### ISSUE TITLE
How to install draw & SSD1607 libs?

### ISSUE THREAD

**Issue by olikraus** [embeddedadventures/EPD-200200B#2]
Please excause asking again. But how exactly do I need to install the two libs?
Are there any install instructions?
I have an Arduino 1.8.0 environment here.

Thanks

**Comment by dr4nc3s** [comment]
I'm running an Arduino 1.6.8 IDE so I'm not sure if any changes were made in library installation. Here is [Arduino's guide](https://www.arduino.cc/en/Guide/Libraries) for installing libraries. 

Let me know if this does the job. I'll leave the issue open until then.

**Comment by olikraus** [comment]
Thanks for the quick response.
Which of the three options mentioned in the "Arduino's guide" shell I use?
For option one, i need to know the library name.
For option two, i need the zip file. Is the zipfile somewhere available?

**Comment by dr4nc3s** [comment]
Let's go with option two. Zip file can be downloaded if you click the green "Clone or Download" button.

**Comment by olikraus** [comment]
Ok, great. I have downloaded both zip files and I have used this zip-lib install feature of the Arduino IDE.
Indeed this works. The example now compiles. Thanks a lot.
