### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by sathibault** [embeddedadventures/EPD-200200B#3]
I'm trying to run the demo on an Atmel SAMD21.  I have two issues:

1. Running the code as is, following the write_command(RamDataEntryMode, sizeof(RamDataEntryMode)) line the device goes into the busy state and never exits.
2. If I comment out this line, all commands succeed but the display is not updated.

**Comment by dr4nc3s** [comment]
I need to test this out on a SAMD21 to figure out what's going on. I'll update you as soon as I have something. Thanks for bringing it to our attention

**Comment by dr4nc3s** [comment]
The library has been updated and tested on a SAMD21-based Arduino board. Try it out and let me know of any issues that pop up.
